# Project-wide Gradle settings.

org.gradle.jvmargs=-Xmx4096m -XX:MaxMetaspaceSize=1024m -XX:+HeapDumpOnOutOfMemoryError
org.gradle.parallel=true

# Android SDK
android.useAndroidX=true
android.enableJetifier=false

# Use Hermes JS engine
hermesEnabled=true

# Use New Architecture (optional)
newArchEnabled=false

# React Native
reactNativeArchitectures=armeabi-v7a,arm64-v8a,x86,x86_64
